# Generated by Django 4.2 on 2023-04-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(blank=True, max_length=6)),
                ('spring_level', models.CharField(blank=True, max_length=6)),
                ('summer_level', models.CharField(blank=True, max_length=6)),
                ('autumn_level', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('fam', models.CharField(max_length=15)),
                ('otc', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'новое'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=8)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinates')),
                ('levels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.level')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('data', models.BinaryField()),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.pass')),
            ],
        ),
    ]
